To Do list: add & remove
denisdiaconu/to-do-list pull request #5
Opened 2021-07-16 15:45 UTC by denisdiaconu

implemented the CRUD (create, update, delete) methods

2021-07-16 17:01 UTC, ZawadiSumba66 requested changes
Hi @denisdiaconu 👋 , 

Great job so far on your project. 👏 👏 
However, there are some issues that you still need to work on to go to the next step but you are almost there! 💪 💪 

## Required Changes ♻️
- [ ] Kindly add an `npm start` in your README at the end of the getting started section to start the server.

_Please check the other comment under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-16 17:01 UTC, ZawadiSumba66 commented on src/dom.js
> +};
- [x] When I check a few several tasks or even a single task and click on the clear completed tasks button, the tasks get unchecked. However, the checked tasks should be removed from the task list. Please fix this.

2021-07-17 00:26 UTC, denisdiaconu commented
Added an npm start in your README.
Fix the remove completed button.

2021-07-17 00:54 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @denisdiaconu🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

![doing good](https://user-images.githubusercontent.com/60631456/126020561-eac6f5fb-369c-4ca6-863d-56effb1c0f84.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-17 00:55 UTC, merged